apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-basic-claim
spec:
  accessModes:
  - ReadWriteOnce
  - ReadOnlyMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
