apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: po-security-context-demo
  name: po-security-context-demo
spec:
  volumes:
  - name: security-context-demo-vol
    emptyDir: {}
  securityContext:
    runAsUser: 1000
    runAsGroup: 2000
    fsGroup: 3000
  containers:
  - image: busybox
    name: security-context-demo-1
    resources: {}
    command: ["sh", "-c", "sleep 1h"]
    volumeMounts:
    - name: security-context-demo-vol
      mountPath: /data/demo/
  - image: busybox
    name: security-context-demo-2
    resources: {}
    command: ["sh", "-c", "sleep 1h"]
    volumeMounts:
    - name: security-context-demo-vol
      mountPath: /data/sec-demo/
  dnsPolicy: ClusterFirst
  restartPolicy: Never
 
status: {}
