apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: sleeper
  name: sleeper
spec:
  containers:
  - command:
    - sleep
    - "100"
    env:
    - name: my_var
      value: my_value
    - name: your_var
      value: your_value
    image: indysreeram/ubuntu-sleeper
    name: sleeper
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
