apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: file-map-test-pod
  name: file-map-test-pod
spec:
  containers:
  - command:
    - env
    envFrom:
    - configMapRef:
        name: file-map
    image: busybox
    name: file-map-test-pod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
