apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: somepod
  name: somepod
spec:
  containers:
  - command:
    - sleep
    - "100"
    envFrom:
            - secretRef:
                name: credentials-secret
            - configMapRef:
                name: credentials-map
    image: busybox
    name: somepod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
