apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: dply-vol-hostpath-test
  name: dply-vol-hostpath-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dply-vol-hostpath-test
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: dply-vol-hostpath-test
    spec:
      volumes:
      - name: anyname
        hostPath:
          path: /home/anand/volumes
      containers:
      - image: busybox
        name: busybox
        command:
        - "sleep"
        - "2h"
        volumeMounts:
        - name: anyname
          mountPath: /data/some/dir
        resources: {}
status: {}
