apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: po-vol-from-cm
  name: po-vol-from-cm-1
spec:
  volumes:
  - name: vol-empty-dir
    emptyDir:
      medium: Memory
  - name: vol-host-path
    hostPath:
      path: /home/anand/volumes
  containers:
  - command:
    - sleep
    - "300"
    image: ubuntu
    name: po-vol-from-cm
    volumeMounts:
    - name: vol-empty-dir
      mountPath: /data/volatile
    - name: vol-host-path
      mountPath: /data/permenent
    env:
    - name: env-key1
      valueFrom:
        configMapKeyRef:
          name: cm-for-vol-test
          key: key1
    - name: env-key2
      valueFrom:
        configMapKeyRef:
          name: cm-for-vol-test
          key: key2
    - name: env-key3
      value: value-3
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
