apiVersion: v1
kind: PersistentVolume

metadata:
  name: pv-standard-1gi

spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  - ReadOnlyMany
  persistentVolumeReclaimPolicy: Recycle

  gcePersistentDisk:
    pdName: standard-1gi
    fsType: ext4
