apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: po-gce-vol-test
  name: po-gce-vol-test
spec:
  volumes:
  - name: gce-persistent-vol
    gcePersistentDisk:
      pdName: sample-disk
  containers:
  - command:
    - sleep
    - "300"
    image: busybox
    name: po-gce-vol-test
    volumeMounts:
    - name: gce-persistent-vol
      mountPath: /data/gce
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
