apiVersion: apps/v1
kind: ReplicaSet

metadata:
  name: rs-nginx
  labels:
    run: nginx

spec:
  replicas: 2
  selector:
    matchLabels:
      run: nginx
  template:
        metadata:
          creationTimestamp: null
          labels:
            run: nginx
          name: nginx
        spec:
          containers:
          - image: nginx
            name: nginx
