apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: sleeper
  name: sleeper
spec:
  containers:
  - args:
    - "100"
    image: indysreeram/ubuntu-sleeper
    name: sleeper
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
